# Generated by Django 4.0.6 on 2022-07-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('description', models.CharField(default='20% off', max_length=255)),
                ('discount', models.FloatField(default=0.2)),
            ],
        ),
    ]
